# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

jobs:
  - job: A
    pool:
      vmImage: 'macos-latest'
    steps:
      - template: build-template.yml
        parameters:
          domain_name: "www.domainA.com"
          app_name: "app_A"

  - job: B
    pool:
      vmImage: 'macos-latest'
    steps:
      - template: build-template.yml
        parameters:
          domain_name: "www.domainB.com"
          app_name: "app_B"

  - job: C
    pool:
      vmImage: 'macos-latest'
    steps:
      - template: build-template.yml
        parameters:
          domain_name: "www.domainC.com"
          app_name: "app_C"